[package]
name = "jono"
version = "0.1.0"
authors = ["m1cl <michael_ajala@yahoo.de>"]
edition = "2018"

[dependencies]
vgtk = "0.3"
pretty_env_logger = "0.4"
keyframe = "1.0.3"
irc = "0.14.1"
rustdoc-stripper = "0.1.16"
